### PR TITLE
Batch of fixes for raspberry pi

### PR DESCRIPTION
**Pull request by danmcgoo**
It seems that this is main repository for the visualization spectrum add-on for Kodi.
Here is a batch of patches that makes the plug-in runs again correctly and smoothly with Kodi 1.6.

I let you check all of them, I think that one might not be correct (the change of priority of OpenGL and OpenGL ES in the CMakeLists.txt) for all platforms, but it makes it compile correctly on a raspberry pi.

### CODE REVIEW

**Comment by notspiff** [comment]
You found the right repo. On my phone so wont review now but just a quick note on the ordering; if we have both availabke and need to choose a particular we need to introduce options to allow disable / enable. I guess one of them suffices (ENABLE_OPENGL after reorder ENABLE_GLES without, no preference from my side).

**Comment by notspiff** [comment]
Other than the mentioned option and the need to check the current droid linker status this looks fine.

**Comment by notspiff** [comment]
hmm, seems to link fine on my droid toolchain. either it was fixed/changed for droid or the problem was on ios. @memphiz ring any bells?

**Comment by Memphiz** [comment]
@notspiff sadly not even the slightest ...

**Comment by danmcgoo** [comment]
Sorry for the late reply, work kept me busy.
To come back to the linker issue, usually when one object is referencing a method of a library by calling it, the linking step will fail if you don't give it the library in which the method is supposed to be located.

Here what I understand is that the only need of the spectrum addon, when it is using OpenGL ES, is the header files (for the structures I suppose). The specific routines for OpenGL ES will be given by VisMatrixGLES.

Concerning the cmake option, you are welcome to add it. Unfortunately, I am not a cmake expert yet >.<

**Pull request closed without merging**
