### PR TITLE
enable OpenGL profile 3.2

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

### CODE REVIEW

**Comment by notspiff** [comment]
merging this as long as we can run with gl < 3.2 is problematic. would it take much to have it run with earlier versions (in my case 3.0) ?

**Comment by FernetMenta** [comment]
this also works for legacy OpenGL

**Comment by notspiff** [comment]
it didn't in my test but i now realize i ran in a dirty tree. works now, so merge whenever it suits you.

**Comment by FernetMenta** [comment]
i donˋt have writes on this repo.

**Comment by notspiff** [comment]
i assume that means merge.

**Pull request merged**
